version: '3'
services:

  pbm:
    image: "dmoriarty/pbm:${RELEASE_VERSION}"
    container_name: pbm
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST_URL: rabbitmq
      SPRING_ACTIVE_PROFILE: "${HOST}"
    command: ["./wait-for-it.sh", "rabbitmq:5672"]
    networks:
      - pbmnet
    volumes:
      - ./target/classes/application.properties:/pbm/application.properties:ro

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - pbmnet
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

networks:
  pbmnet:
    driver: bridge
