---
- name: Configure docker and docker compose on VM
  hosts: vagrant
  become: True
  gather_facts: True
  pre_tasks:
    - name: start vagrant boxes
      command: 'vagrant up'
  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
  tasks:
    - name: start up docker container
      debugger: always
      shell: docker run dmoriarty/pbm:latest

