---
# Example Playbook
- name: Compute Engine Instance Examples
  hosts: localhost
  vars:
    service_account_email: "devops@t-isotope-161616.iam.gserviceaccount.com"
    credentials_file: "~/my_account.json"
    project_id: "t-isotope-161616"
  tasks:
    - name: create multiple instances
      gce:
        instance_names: QAT,UAT,PROD
        zone: us-west1-b
        machine_type: n1-standard-1
        image: debian-8
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata: '{ "startup-script" : "apt-get update" }'
      register: gce

    - name: Save host data
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: gce_instances_ips
      with_items: "{{ gce.instance_data }}"

    - name: Wait for SSH for instances
      wait_for:
        delay: 1
        host: "{{ item.public_ip }}"
        port: 22
        state: started
        timeout: 30
      with_items: "{{ gce.instance_data }}"

- name: Configure Hosts
  hosts: gce_instances_ips
  become: yes
  become_method: sudo
  roles:
    - role: "nickjj.docker"
  tags:
    - ["docker"]
#
#    - name: delete test-instances
#      # Basic termination of instance.
#      gce:
#        service_account_email: "{{ service_account_email }}"
#        credentials_file: "{{ credentials_file }}"
#        project_id: "{{ project_id }}"
#        instance_names: "{{ gce.instance_names }}"
#        zone: us-central1-a
#        state: absent
#      tags:
#        - delete