# Basic provisioning example.  Create a single Debian 8 instance in the
# us-central1-a Zone of the n1-standard-1 machine type.
# Create multiple instances by specifying multiple names, separated by
# commas in the instance_names field
# (e.g. my-test-instance1,my-test-instance2)
gce:
  instance_names: my-test-instance1
  zone: us-central1-a
  machine_type: n1-standard-1
  image: debian-8
  state: present
  service_account_email: "devops@t-isotope-161616.iam.gserviceaccount.com"
  credentials_file: "~/my_account.json"
  project_id: "t-isotope-161616"
  disk_size: 32