VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "bento/ubuntu-18.04"
  end
  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.box = "bento/ubuntu-18.04"
  end
  config.vm.define "vagrant3" do |vagrant3|
    vagrant3.vm.box = "bento/ubuntu-18.04"
    vagrant3.vm.provision "ansible" do |ansible|
      ansible.limit = 'all'
      ansible.playbook = "docker-setup.yml"
    end
  end
end